### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by GabrielLin** [hx364/Chinese_Poem_RNN#1]
C:\Anaconda2\python.exe F:/MyProject_20151101/ChinesePoemRNN/src/model.py
Using Theano backend.
Traceback (most recent call last):
  File "F:/MyProject_20151101/ChinesePoemRNN/src/model.py", line 125, in <module>
    label = to_categorical([i - 1 for i in label])
  File "c:\python_dev\keras-1.0.3\keras\utils\np_utils.py", line 14, in to_categorical
    Y = np.zeros((len(y), nb_classes))
MemoryError

**Comment by hx364** [comment]
I think the reason is your ram is not enough, I used a desktop with 32g ram, and it works fine. I think there are 2 ways: 1) change to another computer 2) modify the code to stream read the data.

**Comment by clovercoser** [comment]
There are too many unique characters(6000+) in qun_tang_shi.txt. I delete it to 4000+, then it works for me.

**Comment by clovercoser** [comment]
@hx364 By the way, there are some errors in your repository because of carelessness.
1. Missing 'return model' in the definition of function train_model 
2. Forget to define 'char_to_index' and 'index_to_char' as global names,  which will be used in function 'make_poem_index'. Define them outside the main function or pass it to function 'make_poem_index' as a parameter.
